import { BillboardSpec, CityMarket } from "./types";

export const BILLBOARD_SPECS: BillboardSpec[] = [
  {
    id: "mega-led",
    name: "Mega LED Spectacle",
    type: "Digital Screen",
    description: "Ultra-bright, premium 8K physical LED array ideal for cinematic loops, 3D anamorphic depth illusions, and dynamic day-night visual sequencing.",
    dimensions: "18m x 12m",
    basePricePerDay: 450,
    estImpressionsPerDay: 850000,
    icon: "MonitorPlay",
  },
  {
    id: "double-decker",
    name: "Transit Cruiser Wrap",
    type: "Mobile Ambient",
    description: "Fully customized wrap enclosing high-frequency double-decker routes. Highly interactive, moving across core central hubs.",
    dimensions: "Full Bus Hull",
    basePricePerDay: 280,
    estImpressionsPerDay: 420000,
    icon: "Truck",
  },
  {
    id: "smart-shelter",
    name: "Urban Smart Shelter",
    type: "Street Furniture",
    description: "Pedestrian-level glass enclosure featuring interactive touchscreen capabilities, Near Field Communication, and targeted geo-fencing.",
    dimensions: "2.4m x 1.8m",
    basePricePerDay: 120,
    estImpressionsPerDay: 95000,
    icon: "Layers",
  },
  {
    id: "eco-cube",
    name: "Solargenix Eco-Cube",
    type: "Special Build",
    description: "Zero-emission, solar-powered kinetic physical standee. Integrates native vertical planting that actively purifies surrounding air.",
    dimensions: "4m x 4m x 4m",
    basePricePerDay: 220,
    estImpressionsPerDay: 130000,
    icon: "Leaf",
  },
];

export const CITY_MARKETS: CityMarket[] = [
  {
    id: "nyc",
    name: "New York City",
    country: "USA",
    reachMultiplier: 1.8,
    premiumFactor: 1.5,
    coordinates: { x: 30, y: 35 },
    popularSpots: ["Times Square Spectacles", "Broadway Hubs", "Fifth Avenue Concourse"],
  },
  {
    id: "london",
    name: "London",
    country: "United Kingdom",
    reachMultiplier: 1.4,
    premiumFactor: 1.3,
    coordinates: { x: 45, y: 25 },
    popularSpots: ["Piccadilly Circus LED", "Kensington High Street", "Waterloo Concourse"],
  },
  {
    id: "tokyo",
    name: "Tokyo",
    country: "Japan",
    reachMultiplier: 1.9,
    premiumFactor: 1.4,
    coordinates: { x: 80, y: 38 },
    popularSpots: ["Shibuya Crossing 3D Wave", "Shinjuku Station Plaza", "Ginza Luxury Avenue"],
  },
  {
    id: "mumbai",
    name: "Mumbai",
    country: "India",
    reachMultiplier: 1.6,
    premiumFactor: 1.1,
    coordinates: { x: 68, y: 55 },
    popularSpots: ["Bandra-Worli Sea Link Mega billboard", "Juhu Radial Promenade", "Andheri Business Boulevard"],
  },
  {
    id: "sydney",
    name: "Sydney",
    country: "Australia",
    reachMultiplier: 1.1,
    premiumFactor: 1.2,
    coordinates: { x: 88, y: 78 },
    popularSpots: ["George Street Transit", "Darling Harbour Bridge-heads", "Pitt Street Podium"],
  },
];

export const STYLE_PRESETS = [
  {
    id: "bold",
    name: "High Intensity Bold",
    textColor: "#ffffff",
    bgColor: "#0c0a0f",
    bgGradient: "linear-gradient(135deg, #111 0%, #000000 100%)",
    fontFamily: "font-bold tracking-normal uppercase italic",
    glowColor: "rgba(255,255,255,0.15)",
    glowSize: "0px 0px 0px",
  },
  {
    id: "neon",
    name: "Cyber Neon Glow",
    textColor: "#39ff14",
    bgColor: "#050014",
    bgGradient: "linear-gradient(135deg, #09001f 0%, #03000b 100%)",
    fontFamily: "font-bold tracking-widest uppercase",
    glowColor: "rgba(57, 255, 20, 0.75)",
    glowSize: "0px 0px 15px",
  },
  {
    id: "luxury",
    name: "Minimalist Luxury",
    textColor: "#d4af37",
    bgColor: "#0a0c10",
    bgGradient: "linear-gradient(135deg, #07090d 0%, #171c26 100%)",
    fontFamily: "font-medium tracking-wide",
    glowColor: "rgba(212, 175, 55, 0.2)",
    glowSize: "0px 0px 8px",
  },
  {
    id: "cyber",
    name: "Acid Purple-Wave",
    textColor: "#ff007f",
    bgColor: "#0d0214",
    bgGradient: "linear-gradient(135deg, #0d0214 0%, #2f0147 100%)",
    fontFamily: "font-bold tracking-tighter uppercase",
    glowColor: "rgba(255, 0, 127, 0.65)",
    glowSize: "0px 0px 12px",
  },
  {
    id: "modern",
    name: "Vibrant Electric Teal",
    textColor: "#00f0ff",
    bgColor: "#031c1b",
    bgGradient: "linear-gradient(135deg, #001211 0%, #012b2a 100%)",
    fontFamily: "font-bold tracking-normal",
    glowColor: "rgba(0, 240, 255, 0.5)",
    glowSize: "0px 0px 10px",
  },
];
